### ISSUE TITLE
Google Oauth

### ISSUE THREAD

**Issue by JakeAlvarado** [splitit-app/splitit#50]
_**Description:**_ 
`As a user of the app I would like to sign in with my Google account. I would also like to be able to sign up with my Google account if possible.`

**Comment by Priyank295** [comment]
> _**Description:**_ `As a user of the app I would like to sign in with my Google account. I would also like to be able to sign up with my Google account if possible.`

I can try to make google auth functionality

**Comment by JakeAlvarado** [comment]
Thanks for support Priyank, for this specific issue I'm close to a full implementation at the moment but if any other issues catch your eye leave a comment for one of the other developers as well!

**Comment by JakeAlvarado** [comment]
Tested invalid Gmail email. Successfully rejects non-google affiliated email.

**Comment by JakeAlvarado** [comment]
Issues with account creation after google account creation. Discovered bloc package issue and resolved.

**Comment by JakeAlvarado** [comment]
Bug: Google account creation not available to all machines utilizing application. Installed SHA-1 certificates pertaining to each device to allow Google Oauth verification. Further certificate signing necessary for release build if automatic verification is needed.

**Comment by JakeAlvarado** [comment]
Feature implemented
