### ISSUE TITLE
Exact Split (dialog stretches to the bottom of screen)

### ISSUE THREAD

**Issue by TastyMeat** [splitit-app/splitit#57]

**Comment by JakeAlvarado** [comment]
New classification for the bug:
Dialog box does not pop up and instead crashes the application

**Comment by JakeAlvarado** [comment]
Removed the Expanded() wrapper around the TextField seems to be causing a UI crash due to sizing constraints of the column widget

**Comment by JakeAlvarado** [comment]
Dialog box works as intended, and adjust's values based on value entered into the dialog box. Can now edit friends exact amounts.
